version: "3.9"
services:
  backend:
    build: .
    image: "backend:latest"
    container_name: "ducnd_backend"
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    container_name: "ducnd_redis"
    ports:
      - "6379:6379"