version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: "redis:lastest"
    ports:
      - "6379:6379"